import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Jim's Finance Tracker",
    short_name: "Jim's Finance",
    description: "Track every dollar, from subscriptions to coffee",
    start_url: '/dashboard',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait-primary',
    background_color: '#fffbe6',
    theme_color: '#ff6b35',
    categories: ['finance', 'productivity'],
    icons: [
      // SVG — scales to any resolution, used by modern Android Chrome
      {
        src: '/icons/icon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
        purpose: 'any',
      },
      // Maskable SVG — adaptive icon with safe-zone padding
      {
        src: '/icons/icon-maskable.svg',
        sizes: 'any',
        type: 'image/svg+xml',
        purpose: 'maskable',
      },
      // Apple touch icon (PNG, generated by Next.js app/apple-icon.tsx)
      {
        src: '/apple-icon',
        sizes: '180x180',
        type: 'image/png',
        purpose: 'any',
      },
    ],
  };
}
